### ISSUE TITLE
 Upgrade to 1.19

### ISSUE THREAD

**Issue by Toub** [jagregory/pandoc-docker#10]
Could you update this container to the latest pandoc version?

And also consider contributing directly to the official pandoc repository: https://github.com/jgm/pandoc/issues/3399

**Comment by jagregory** [comment]
Pull requests are appreciated. This change should be straight forward and
is a good opportunity to contribute.

**Comment by Toub** [comment]
Ok. About my second question, what do you think about submitting a pull request to pandoc project (and merge with) ?

However, there is an issue about integrating your work to pandoc official directory, as your license GPL3 is more restrictive than pandoc's one (GPL2+).

Could you consider upgrading to the exact same license?

This would require the agreement of contributers: @cameronbrunner and @oncletom 

Else, we should start a new Dockerfile from scratch.

**Comment by jagregory** [comment]
I'm happy to relicense, and I'd be glad to contribute to the official repo
if the maintainers are interested.

**Comment by cameronbrunner** [comment]
FWIW I have absolutely no problem with a relicense.

**Comment by Toub** [comment]
Great, what about @oncletom?

**Comment by Toub** [comment]
@oncletom are you OK with a relicence from GPL3 to GPL2+ in order to be compatible with pandoc licence?

**Comment by oncletom** [comment]
Hm, I'm not sure to understand where is located the GPLv3 license you are referring to – I only spotted https://github.com/jagregory/pandoc-docker/blob/master/LICENSE which is MIT.

In any case, I guess the closer to the users the Dockerfile is, the better it is.
So up for it to relicense from GPL3 to GPL2 to comply with pandoc license.

**Comment by Toub** [comment]
My bad, you are right, this project is licensed under the MIT!

Anyway, the problem is identical, we have to relicense to GPL2+ (note that GPL2+ means GPL2/GPL3/...).

An other option is to keep both (MIT + GPL2+).

@jagregory we are waiting for your action (merge 1.19 PR and GPL2+ relicense).

Then, the discussion continues there: https://github.com/jgm/pandoc/issues/3399

**Comment by jagregory** [comment]
Pull request merged, and relicensed.

**Comment by Toub** [comment]
Sorry, but GPL2 != GPL2+

GPL2 is not compatible with GPL3, so it is not compatible with GPL2+ (GPL either version 2 of the License, or any later version) .

So at least, add the following in the very top of the LICENSE file:
```
Released under the GPL, version 2 or greater. 
```

**Comment by Toub** [comment]
Then, would you like to submit a PR with your last Dockerfile to the main pandoc project, with a reference to https://github.com/jgm/pandoc/issues/3399

Thanks!
